### ISSUE TITLE
Can't install sqlite when using ruby 2.7 and engine_cart 2.6.0

### ISSUE THREAD

**Issue by jcoyne** [cbeer/engine_cart#128]
Despite this code: https://github.com/cbeer/engine_cart/blob/9bdcb81be41cedbbe210c04f458a7792ac49e625/lib/engine_cart/tasks/engine_cart.rake#L80-L87

We still seem to have this problem:
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/sqlite3-1.7.0/ext/sqlite3
/opt/hostedtoolcache/Ruby/2.7.8/x64/bin/ruby -I
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/2.7.0 -r
./siteconf20240118-2773-1o6hqk8.rb extconf.rb
Building sqlite3-ruby using packaged sqlite3.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/hostedtoolcache/Ruby/2.7.8/x64/bin/$(RUBY_BASE_NAME)
	--help
	--download-dependencies
	--with-sqlcipher
	--without-sqlcipher
	--with-sqlcipher-dir
	--without-sqlcipher-dir
	--with-sqlcipher-include
	--without-sqlcipher-include
	--with-sqlcipher-lib
	--without-sqlcipher-lib
	--enable-system-libraries
	--disable-system-libraries
	--with-sqlcipher
	--without-sqlcipher
	--with-sqlcipher-dir
	--without-sqlcipher-dir
	--with-sqlcipher-include
	--without-sqlcipher-include
	--with-sqlcipher-lib
	--without-sqlcipher-lib
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/2.7.0/psych.rb:456:in
`parse_stream': undefined method `parse' for #<Psych::Parser:0x000055ac9f2668e8>
(NoMethodError)
	from /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/2.7.0/psych.rb:390:in `parse'
	from /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/2.7.0/psych.rb:277:in `load'
from /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/2.7.0/psych.rb:578:in `block
in load_file'
	from /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/2.7.0/psych.rb:577:in `open'
from /opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/2.7.0/psych.rb:577:in
`load_file'
	from extconf.rb:162:in `mini_portile_config'
	from extconf.rb:157:in `sqlite3_config'
	from extconf.rb:141:in `minimal_recipe'
	from extconf.rb:51:in `configure_packaged_libraries'
	from extconf.rb:17:in `configure'
	from extconf.rb:285:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in
/opt/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/sqlite3-1.7.0 for
inspection.
```

**Comment by jcoyne** [comment]
This later problem seems to be due to using the bundler cache built into Github actions.

**Comment by jcoyne** [comment]
Ruby 2 is EOL.
