### ISSUE TITLE
uninitialized constant Devise with 0.8.0

### ISSUE THREAD

**Issue by jcoyne** [cbeer/engine_cart#38]
Worked with 0.7.1
```
...
Coverage report sent to Coveralls.

/home/travis/build/projecthydra-labs/curation_concerns/.internal_test_app/config/initializers/devise.rb:3:in `<top (required)>': uninitialized constant Devise (NameError)

	from /home/travis/build/projecthydra-labs/curation_concerns/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/engine.rb:652:in `block in load_config_initializer'

	from /home/travis/build/projecthydra-labs/curation_concerns/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:166:in `instrument'

	from /home/travis/build/projecthydra-labs/curation_concerns/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/engine.rb:651:in `load_config_initializer'

	from /home/travis/build/projecthydra-labs/curation_concerns/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'

	from /home/travis/build/projecthydra-labs/curation_concerns/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/engine.rb:615:in `each'

	from /home/travis/build/projecthydra-labs/curation_concerns/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/engine.rb:615:in `block in <class:Engine>'

	from /home/travis/build/projecthydra-labs/curation_concerns/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'

	from /home/travis/build/projecthydra-labs/curation_concerns/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'

	from /home/travis/build/projecthydra-labs/curation_concerns/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'

	from /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'

	from /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'

	from /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'

	from /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'

	from /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'

	from /home/travis/build/projecthydra-labs/curation_concerns/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `each'

	from /home/travis/build/projecthydra-labs/curation_concerns/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:44:in `tsort_each_child'

	from /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:413:in `call'

	from /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'

	from /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'

	from /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each'

	from /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `call'

	from /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'

	from /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'

	from /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'

	from /home/travis/build/projecthydra-labs/curation_concerns/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'

	from /home/travis/build/projecthydra-labs/curation_concerns/vendor/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'

	from /home/travis/build/projecthydra-labs/curation_concerns/.internal_test_app/config/environment.rb:5:in `<top (required)>'

	from /home/travis/build/projecthydra-labs/curation_concerns/vendor/bundle/ruby/2.2.0/gems/engine_cart-0.8.0/lib/engine_cart.rb:14:in `require'

	from /home/travis/build/projecthydra-labs/curation_concerns/vendor/bundle/ruby/2.2.0/gems/engine_cart-0.8.0/lib/engine_cart.rb:14:in `load_application!'

	from /home/travis/build/projecthydra-labs/curation_concerns/spec/spec_helper.rb:11:in `<top (required)>'

	from /home/travis/build/projecthydra-labs/curation_concerns/spec/abilities/collection_abilities_spec.rb:1:in `require'

	from /home/travis/build/projecthydra-labs/curation_concerns/spec/abilities/collection_abilities_spec.rb:1:in `<top (required)>'

	from /home/travis/build/projecthydra-labs/curation_concerns/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `load'

	from /home/travis/build/projecthydra-labs/curation_concerns/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `block in load_spec_files'

	from /home/travis/build/projecthydra-labs/curation_concerns/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `each'

	from /home/travis/build/projecthydra-labs/curation_concerns/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `load_spec_files'

	from /home/travis/build/projecthydra-labs/curation_concerns/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:102:in `setup'

	from /home/travis/build/projecthydra-labs/curation_concerns/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:88:in `run'

	from /home/travis/build/projecthydra-labs/curation_concerns/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'

	from /home/travis/build/projecthydra-labs/curation_concerns/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'

	from /home/travis/build/projecthydra-labs/curation_concerns/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/exe/rspec:4:in `<main>'
```

**Comment by jcoyne** [comment]
Added upgrade guide: https://github.com/cbeer/engine_cart/releases/tag/v0.8.0
