### ISSUE TITLE
Turn listen off?

### ISSUE THREAD

**Issue by jcoyne** [cbeer/engine_cart#62]
Under rails 5, generating the application hangs at `generate  blacklight:solr5`. When I break out of the process, I see some errors with `fsevent`

```
$ bundle exec rake engine_cart:generate
      create
/Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/2.3.0/fileutils.rb:128: warning: conflicting chdir during another chdir block
      create  README.md
      create  Rakefile
...
  test_app
    generate  sufia:install
        info  GENERATING SUFIA
    generate  curation_concerns:install --skip-assets -f
     warning  [CurationConcerns] GENERATING BLACKLIGHT
    generate  blacklight:install --devise
    generate  blacklight:solr5
^CThere was a Errno::E260 while loading sufia.gemspec:
Unknown error: 260 - git from
  /Users/jcoyne/workspace/sufia/sufia.gemspec:13:in ``'

E, [2016-08-25T10:25:55.684127 #70662] ERROR -- : fsevent: running worker failed: Resource temporarily unavailable - /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/bin/fsevent_watch:/Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/lib/rb-fsevent/fsevent.rb:106:in `popen'
/Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/lib/rb-fsevent/fsevent.rb:106:in `open_pipe'
/Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rb-fsevent-0.9.7/lib/rb-fsevent/fsevent.rb:37:in `run'
/Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/listen-3.0.8/lib/listen/adapter/darwin.rb:68:in `_run_worker'
/Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/listen-3.0.8/lib/listen/adapter/darwin.rb:77:in `block (2 levels) in _run_workers_in_background'
/Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/listen-3.0.8/lib/listen/internals/thread_pool.rb:6:in `block in add' called from: /Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/listen-3.0.8/lib/listen/adapter/darwin.rb:67:in `_run_worker'
/Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/listen-3.0.8/lib/listen/adapter/darwin.rb:77:in `block (2 levels) in _run_workers_in_background'
/Users/jcoyne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/listen-3.0.8/lib/listen/internals/thread_pool.rb:6:in `block in add'
...
```

**Comment by jcoyne** [comment]
```
ENGINE_CART_RAILS_OPTIONS="--skip_listen" bundle exec rake engine_cart:generate
```
seems to fix the problem for me.  Is this an issue for anyone else?

**Comment by cbeer** [comment]
Yep, I ran into that yesterday too with sufia. I'm hoping we can find a better approach (or report a bug upstream), since `listen` seems genuinely useful in development.

**Comment by cbeer** [comment]
This is probably related to https://github.com/rails/rails/issues/26158.

In `1.0.0`, I added support for reading options from configuration files, as demonstrated here: https://github.com/projecthydra/sufia/pull/2552.
